name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc make bochs bochs-sdl grub2

      - name: Build project
        run: make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-project
          path: ./build/
          
